pcamarillor/P2025_ESI3914B

- .gitignore
- README.md
- spark_cluster/README.md
- spark_cluster/build-images.bat
- spark_cluster/build-images.sh
- spark_cluster/docker-compose.yml
- spark_cluster/docker/base/Dockerfile
- spark_cluster/docker/jupyter-notebook/Dockerfile
- spark_cluster/docker/kafka-producer/Dockerfile
- spark_cluster/docker/spark-master/Dockerfile
- spark_cluster/docker/spark-master/start-master.sh
- spark_cluster/docker/spark-worker/Dockerfile
- spark_cluster/docker/spark-worker/start-worker.sh
- spark_cluster/run_kafka_producer.sh
- spark_cluster/spark-submit-cluster.bat
- spark_cluster/spark-submit-cluster.sh
- spark_cluster/start_jupyter.sh
Adding docker files to launch the local spark cluster with Apache Spark 3..5.4 and Scala 2.13
> Adding resources to build the spark cluster

- README.md
> Team names lecture03

- spark_cluster/notebooks/labs/lab01/lab01_JoseCota.ipynb
Code Lab 01: Student Grade Analyzer
> Lab01 Jose Cota

- spark_cluster/notebooks/labs/lab02/lab02_MarcoAlbanese.ipynb
> Lab02 Marco Albanese

- spark_cluster/notebooks/labs/lab02/lab02_AndresBlanco.ipynb
> Lab 02 Andres

- spark_cluster/notebooks/labs/lab02/lab02_JoseCota.ipynb
Code Lab 02: Dynamic Function Execution Using a Dictionary
> Lab02_JoseCota

- spark_cluster/notebooks/labs/lab02/lab02_Tirzah.ipynb
> lab02_TirzahPenicheBarba

- spark_cluster/notebooks/labs/lab01/lab01_MarcoAlbanese.ipynb
> Lab01 Marco Albanese

- spark_cluster/notebooks/labs/lab03/lab03_MarcoAlbanese.ipynb
> Lab03 MarcoAlbanese

- spark_cluster/notebooks/labs/lab03/lab03_Angel_Cortes.ipynb
> Lab03 angel cortes

- spark_cluster/notebooks/labs/lab03/lab03_NaranjoSalgadoDavidAbraham.ipynb
> Lab 3 terminado

- spark_cluster/notebooks/labs/lab03/lab03_Tirzah.ipynb
Se agrega laboratorio 3 con variaciones de la salida según el formato solicitado.
> Lab03_Tirzah

- spark_cluster/notebooks/labs/lab03/lab03_AlejandroRomero.ipynb
> AlejandroRomero_Lab03

- spark_cluster/notebooks/labs/lab04/lab04_ArribaLinux.ipynb
- spark_cluster/notebooks/lib/ArribaLinux/spark_utils.py
Archivos para crear schema de datos con ejemplo de su funcionamiento y muestra de que los datos sí fueron modificados exitosamente
> Lab04 arriba linux

- spark_cluster/notebooks/labs/lab04/lab04_EquipoMcQueen.ipynb
- spark_cluster/notebooks/lib/equipo_mcqueen/spark_utils.py
> Lab04_equipo_McQueen

- spark_cluster/notebooks/labs/lab05/lab05_ArribaLinux.ipynb
- spark_cluster/notebooks/lib/ArribaLinux/spark_utils.py
> Lab05 arriba linux

- spark_cluster/notebooks/exams/midterm/exam_marco_albanese.ipynb
> Examen 1 Marco Albanese

- spark_cluster/notebooks/exams/midterm/Alejandro-Romero-examen.ipynb
> Examen Alejandro Samuel Romero Mora

- kafka_cluster/docker-compose.yml
- spark_cluster/notebooks/examples/example_structured_streaming_kafka.ipynb
> Adding resources for lecture 20

- spark_cluster/notebooks/labs/lab08/lab08_EquipoMcQueen.ipynb
> Lab08 Equipo McQueen

- spark_cluster/notebooks/labs/lab12/lab12_ArribaLinux.ipynb
> Lab 12 terminado
